project:
  type: website
  output-dir: docs
  render:
    - index.qmd
  resources:
    - CNAME
    - .nojekyll
    - columbo_final.webm
  
  

website:
  title: "FMA Tutorial"

format:
  html:
    theme: default